version: "3.8"

services:

  awsgi:
    build: .
    working_dir: /app
    command: python3 run.py
    env_file:
      - .env
    ports:
      - "8013:8013"
    network_mode: "host"


  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env
    ports:
      - "5432:5432"
    network_mode: "host"


